#!/usr/bin/env bash
# =============================================================================
# Cognito — health check (v1.2.0)
# =============================================================================
# Ran by `/cognition-status --verify` (or directly).
# Reports OK / WARN / FAIL per check. Exit code != 0 if any FAIL.
#
# Usage:
#   bash scripts/cognition-verify.sh
#   bash scripts/cognition-verify.sh --target=/custom/path
#   bash scripts/cognition-verify.sh --settings=/custom/settings.json
#   bash scripts/cognition-verify.sh --json            # machine-readable
#   bash scripts/cognition-verify.sh --repair          # v1.2: fix corruption
#
# --repair semantics:
#   * If config/_phase-state.json is missing or not valid JSON, it is replaced
#     with a fresh copy of _phase-state.default.json.
#   * If config/_phase-state.default.json is missing, a minimal default is
#     synthesized in-memory (only happens on a very broken install).
#   * Every repair action appends a line to logs/incidents.log so the fix is
#     auditable after the fact. --repair never touches user content (logs,
#     sessions, commands, settings.json).
# =============================================================================

set -uo pipefail

TARGET_DIR="${HOME}/.claude/cognito"
SETTINGS_FILE="${HOME}/.claude/settings.json"
JSON_OUT=0
REPAIR=0

for arg in "$@"; do
    case "$arg" in
        --target=*)   TARGET_DIR="${arg#*=}"    ;;
        --settings=*) SETTINGS_FILE="${arg#*=}" ;;
        --json)       JSON_OUT=1                ;;
        --repair)     REPAIR=1                  ;;
        --help|-h)
            cat <<'EOF'
Usage: bash scripts/cognition-verify.sh [options]

Options:
  --target=PATH     install dir (default: ~/.claude/cognito)
  --settings=PATH   settings.json (default: ~/.claude/settings.json)
  --json            emit JSON lines instead of human-readable
  --repair          attempt to fix corrupted state (see script header)
EOF
            exit 0
            ;;
    esac
done

export TARGET_DIR SETTINGS_FILE JSON_OUT REPAIR

python3 <<'PYEOF'
import importlib.util
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

TARGET = Path(os.environ["TARGET_DIR"])
SETTINGS = Path(os.environ["SETTINGS_FILE"])
JSON_OUT = os.environ.get("JSON_OUT") == "1"
REPAIR = os.environ.get("REPAIR") == "1"

results = []
repairs = []  # v1.2: (what, action, outcome) tuples when --repair is on


def check(name: str, status: str, detail: str = ""):
    """status in {ok, warn, fail}."""
    results.append({"name": name, "status": status, "detail": detail})


def _append_incident(line: str) -> None:
    """Append a line to logs/incidents.log. Never raises."""
    try:
        log_dir = TARGET / "logs"
        log_dir.mkdir(parents=True, exist_ok=True)
        incidents = log_dir / "incidents.log"
        from datetime import datetime, timezone
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        with open(incidents, "a", encoding="utf-8") as f:
            f.write(f"[{ts}] {line}\n")
    except Exception:  # noqa: BLE001
        pass


def _default_phase_state() -> dict:
    """Minimal synthesized default in case the bundled default is also missing."""
    from datetime import datetime, timezone
    return {
        "version": "1.0",
        "description": "Estado de la fase actual (regenerated by --repair).",
        "current": "discovery",
        "since": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "previousPhases": [],
        "overrideModes": [],
        "sessionId": None,
        "lastUpdatedBy": "cognition-verify --repair",
    }


def repair_phase_state() -> tuple[bool, str]:
    """Return (did_repair, detail). Never raises."""
    state_file = TARGET / "config" / "_phase-state.json"
    default_file = TARGET / "config" / "_phase-state.default.json"

    broken = False
    if not state_file.is_file():
        broken = True
        reason = "missing"
    else:
        try:
            json.loads(state_file.read_text(encoding="utf-8"))
        except Exception:  # noqa: BLE001
            broken = True
            reason = "invalid JSON"

    if not broken:
        return False, ""

    # Build fallback content.
    fallback: dict
    if default_file.is_file():
        try:
            fallback = json.loads(default_file.read_text(encoding="utf-8"))
            source = "_phase-state.default.json"
        except Exception:  # noqa: BLE001
            fallback = _default_phase_state()
            source = "synthesized-default (bundled default also unreadable)"
    else:
        fallback = _default_phase_state()
        source = "synthesized-default"

    # Backup the broken file for forensics, then overwrite atomically.
    try:
        if state_file.is_file():
            import shutil
            from datetime import datetime, timezone
            ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
            backup = state_file.with_name(f"_phase-state.broken.{ts}.json")
            shutil.copy(state_file, backup)
        tmp = state_file.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(fallback, indent=2), encoding="utf-8")
        os.replace(tmp, state_file)
    except Exception as e:  # noqa: BLE001
        _append_incident(f"phase-state repair FAILED ({reason}): {e}")
        return False, f"tried but failed: {e}"

    detail = f"{reason}; restored from {source}"
    _append_incident(f"phase-state repaired ({reason}); source={source}")
    repairs.append({"target": "config/_phase-state.json", "action": "restore", "detail": detail})
    return True, detail

# 1. Python version
py = sys.version_info
if py >= (3, 10):
    check("python-3.10+", "ok", f"python {py.major}.{py.minor}.{py.micro}")
else:
    check("python-3.10+", "fail", f"found {py.major}.{py.minor}; Cognito requires 3.10+")

# 2. jq present (strongly recommended for install/uninstall settings.json merge)
if shutil.which("jq"):
    check("jq", "ok")
else:
    check("jq", "warn", "jq not on PATH — install.sh falls back to printing snippet")

# 3. Install dir exists
if TARGET.is_dir():
    check("install-dir", "ok", str(TARGET))
else:
    check("install-dir", "fail", f"not found: {TARGET}")
    # Early exit: nothing else works without the install dir.
    for r in results:
        if JSON_OUT:
            print(json.dumps(r))
        else:
            icon = {"ok": "ok  ", "warn": "warn", "fail": "FAIL"}[r["status"]]
            print(f"[{icon}] {r['name']:<24} {r['detail']}")
    sys.exit(1 if any(r["status"] == "fail" for r in results) else 0)

# 4. Each config JSON exists and parses. --repair can auto-fix _phase-state.
EXPECTED_JSONS = [
    "_modes.json",
    "_phases.json",
    "_passive-triggers.json",
    "_operator-config.json",
    "_phase-state.json",
    "_phase-state.default.json",
]

# Try to auto-repair _phase-state.json first so subsequent checks see the
# restored file instead of a dangling fail.
if REPAIR:
    did, detail = repair_phase_state()
    if did:
        check("repair/_phase-state.json", "ok", detail)

for name in EXPECTED_JSONS:
    path = TARGET / "config" / name
    if not path.is_file():
        check(f"config/{name}", "fail", "missing")
        continue
    try:
        with open(path, encoding="utf-8") as f:
            json.load(f)
        check(f"config/{name}", "ok")
    except Exception as e:
        check(f"config/{name}", "fail", f"invalid JSON: {e}")

# 5. Regex patterns compile (passive-triggers)
try:
    with open(TARGET / "config" / "_passive-triggers.json", encoding="utf-8") as f:
        trig = json.load(f)
    bad = 0
    for rule in trig.get("gates", {}).get("rules", []):
        pat = rule.get("pattern", "")
        try:
            re.compile(pat)
        except re.error:
            bad += 1
    for rule in trig.get("anchorDetection", {}).get("rules", []):
        pat = rule.get("pattern", "").lower().replace("[x]", ".+")
        if not pat:
            continue
        try:
            re.compile(pat)
        except re.error:
            bad += 1
    if bad == 0:
        check("regex-patterns", "ok", "all regex patterns compile")
    else:
        check("regex-patterns", "warn", f"{bad} pattern(s) failed to compile")
except Exception as e:
    check("regex-patterns", "warn", f"could not inspect: {e}")

# 6. Hook scripts present + executable
HOOKS = ["phase-detector.sh", "mode-injector.sh", "gate-validator.sh", "session-closer.sh"]
for h in HOOKS:
    path = TARGET / "hooks" / h
    if not path.is_file():
        check(f"hooks/{h}", "warn", "missing (profile may not install this hook)")
        continue
    mode = path.stat().st_mode
    if mode & 0o111:
        check(f"hooks/{h}", "ok")
    else:
        check(f"hooks/{h}", "warn", "not executable (chmod +x)")

# 7. settings.json has the Cognito hooks registered
if not SETTINGS.is_file():
    check("settings.json", "warn", f"not found: {SETTINGS}")
else:
    try:
        with open(SETTINGS, encoding="utf-8") as f:
            stg = json.load(f)
        hooks_block = (stg or {}).get("hooks") or {}
        installed_hooks = [h for h in HOOKS if (TARGET / "hooks" / h).is_file()]
        registered = set()
        for event, entries in hooks_block.items():
            for entry in entries or []:
                if not isinstance(entry, dict):
                    continue
                # Legacy non-standard shape: top-level "cognito-*" name.
                name = entry.get("name", "")
                if name.startswith("cognito-"):
                    registered.add(name.replace("cognito-", "") + ".sh")
                # Standard Claude Code schema: matcher-group with hooks[].command.
                for cmd_obj in entry.get("hooks") or []:
                    cmd = (cmd_obj or {}).get("command", "") if isinstance(cmd_obj, dict) else ""
                    for base in HOOKS:
                        if cmd.endswith("/hooks/" + base):
                            registered.add(base)
        missing = [h for h in installed_hooks if h not in registered]
        if not installed_hooks:
            check("settings-hooks", "warn", "no hooks installed to register")
        elif not missing:
            check("settings-hooks", "ok", f"{len(registered)} Cognito hook(s) registered")
        else:
            check("settings-hooks", "warn", f"unregistered: {', '.join(missing)}")
    except Exception as e:
        check("settings-hooks", "warn", f"could not read settings.json: {e}")

# 8. _phase-state writable
ps = TARGET / "config" / "_phase-state.json"
if ps.is_file() and os.access(ps, os.W_OK):
    check("phase-state-writable", "ok")
else:
    check("phase-state-writable", "fail", f"{ps} not writable")

# 9. logs dir and sessions dir writable
for d in ("logs", "sessions"):
    path = TARGET / d
    try:
        path.mkdir(parents=True, exist_ok=True)
        test_file = path / ".verify-write-test"
        test_file.write_text("ok", encoding="utf-8")
        test_file.unlink()
        check(f"{d}-writable", "ok")
    except Exception as e:
        check(f"{d}-writable", "fail", str(e))

# 10. Sinapsis bridge: detectable or cleanly opt-out
try:
    bridge_path = TARGET / "integrations" / "sinapsis_bridge.py"
    op_cfg_path = TARGET / "config" / "_operator-config.json"
    op_cfg = {}
    if op_cfg_path.is_file():
        op_cfg = json.loads(op_cfg_path.read_text(encoding="utf-8"))
    sinapsis_declared = (op_cfg.get("integrations", {}) or {}).get("sinapsis", {}) or {}
    declared_installed = sinapsis_declared.get("installed", None)
    if not bridge_path.is_file():
        check("sinapsis-bridge", "warn", "bridge script missing (standalone mode)")
    else:
        # Try to import and run detect()
        sys.path.insert(0, str(TARGET / "integrations"))
        try:
            import importlib
            spec = importlib.util.spec_from_file_location("sinapsis_bridge", bridge_path)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            bridge = mod.SinapsisBridge.detect(operator_config=op_cfg)
            if bridge.available:
                check("sinapsis-bridge", "ok", f"detected v{bridge.version or '?'}")
            elif declared_installed is False:
                check("sinapsis-bridge", "ok", "opt-out honored (integrations.sinapsis.installed=false)")
            else:
                check("sinapsis-bridge", "ok", "standalone (no Sinapsis install detected)")
        except Exception as e:
            check("sinapsis-bridge", "warn", f"bridge import failed: {e}")
except Exception as e:
    check("sinapsis-bridge", "warn", str(e))

# ----- Emit results ----------------------------------------------------------
has_fail = any(r["status"] == "fail" for r in results)
n_warn = sum(1 for r in results if r["status"] == "warn")
n_ok = sum(1 for r in results if r["status"] == "ok")

if JSON_OUT:
    for r in results:
        print(json.dumps(r))
    if REPAIR and repairs:
        for rep in repairs:
            print(json.dumps({"repair": rep}))
else:
    print("Cognito health check")
    print("=" * 56)
    for r in results:
        icon = {"ok": "ok  ", "warn": "WARN", "fail": "FAIL"}[r["status"]]
        detail = f" -- {r['detail']}" if r["detail"] else ""
        print(f"[{icon}] {r['name']:<26}{detail}")
    print("=" * 56)
    print(f"Summary: {n_ok} ok, {n_warn} warn, {sum(1 for r in results if r['status'] == 'fail')} fail")
    if REPAIR:
        if repairs:
            print(f"Repaired: {len(repairs)} item(s); see {TARGET / 'logs' / 'incidents.log'}")
        else:
            print("Nothing to repair.")

sys.exit(1 if has_fail else 0)
PYEOF
